### PR TITLE
Add test_skip_conditions_from_repeating_group_based_on_non_repeating_answer.json

### PR DESCRIPTION
**Pull request by kierenbeckett**
Add test_skip_conditions_from_repeating_group_based_on_non_repeating_answer.json

### CODE REVIEW

**Review by jonnyshaw89 — APPROVED** [review]
If you shorten the commit message please

**Comment by kierenbeckett** [comment]
What's our limit?

**Comment by jonnyshaw89** [comment]
Ah, I saw the `...` and thought it had been truncated by GitHub
Maybe just split it across 2 lines so we don't need to truncate to keep gitHub happy?
eg
Added missing test schema
test_skip_conditions_from_repeating_group_based_on_non_repeating_answer.json

**Review by benhowes — APPROVED** [review]

**Comment by benhowes** [comment]
@kierenbeckett needs rebasing please :)

**Pull request merged**
