### PR TITLE
Replace arrow function with ES5 syntax to allow to work in IE

### LINKED ISSUE #124: Launcher page does not run in IE
Javascript errors in IE due to ES6 syntax (arrow function) in launch.html template.

### PR DESCRIPTION
**Pull request by bameyrick**
Javascript written within script tags in templates is not run through babel therefore isn't transpiled to ES5.

Resolves #124

### CODE REVIEW

**Comment by jonnyshaw89** [comment]
I think there is another issue
screenshot 2018-11-02 at 12 05 18

**Comment by bameyrick** [comment]
@jonnyshaw89 I've added a UUID generator that will work in IE which should resolve this 👍

**Review by jonnyshaw89 — APPROVED** [review]

**Review by bitdivision — APPROVED** [review]
Tested working :+1:

**Comment by bitdivision** [comment]
@bameyrick 	Squishy Squash

**Comment by jonnyshaw89** [comment]
Commits make sense on their own as they are separate changes

**Pull request merged**
