### PR TITLE
EAR-1142  Add gh actions

### PR DESCRIPTION
**Pull request by tjamesmac**
### Context

Adds gh actions to go launcher instead of travis

### CODE REVIEW

**Review by MattElcock — DISMISSED** [review]

**Comment by tbaggaley** [comment]
Unless I'm missing something the new GA doesn't compile the go stuff? Thinking about these lines from the old Travis file:

```
 - go get -t ./...
 - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo
 ```

Are they needed before we build / push the Docker file? I'm not familiar with the Go toolchain but it looks as though there's a compilation step in the old one before it makes the Docker image

**Comment by MattElcock** [comment]
> Unless I'm missing something the new GA doesn't compile the go stuff? Thinking about these lines from the old Travis file:
> 
> ```
>  - go get -t ./...
>  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo
> ```
> 
> Are they needed before we build / push the Docker file? I'm not familiar with the Go toolchain but it looks as though there's a compilation step in the old one before it makes the Docker image

It's in the Dockerfile. Travis didn't need to do those two lines you've quoted, it turns out. Before Docker builds the image, it copies the source code, grabs the dependencies and compiles the application.

**Review by tbaggaley — APPROVED** [review]
Okay, cool

**Comment by jasehumphr** [comment]
Martyn's name is all over this

**Review by zimboflyman — APPROVED** [review]

**Pull request merged**
